### ISSUE TITLE
New cluster singularity issue

### ISSUE THREAD

**Issue by alsmith151** [alsmith151/SeqNado#77]
WorkflowError:
Failed to pull singularity image from library://asmith151/seqnado/seqnado_pipeline:latest:
FATAL:   Unable to get library client configuration: remote has no library client (see https://apptainer.org/docs/user/latest/endpoint.html#no-default-remote)

Fix:

apptainer remote add --no-login SylabsCloud cloud.sylabs.io
apptainer remote use SylabsCloud

**Comment by CChahrour** [comment]
Moved singularity to FAQ in docs
